import json
from decimal import Decimal, InvalidOperation

from django.conf import settings
from openai import OpenAI

from .models import ListingRequest, ListingResult


def _to_decimal(value):
    if value in (None, "", "null"):
        return None
    try:
        return Decimal(str(value))
    except (InvalidOperation, TypeError, ValueError):
        return None


def build_prompt_data(listing_request: ListingRequest) -> dict:
    return {
        "item_name": listing_request.item_name,
        "category": listing_request.category,
        "platform": listing_request.platform,
        "condition": listing_request.condition,
        "tone": listing_request.tone,
        "brand": listing_request.brand or "",
        "size_details": listing_request.size_details or "",
        "color": listing_request.color or "",
        "material": listing_request.material or "",
        "flaws": listing_request.flaws or "",
        "raw_notes": listing_request.raw_notes or "",
    }


def generate_listing_result(listing_request: ListingRequest) -> ListingResult:
    client = OpenAI(api_key=settings.OPENAI_API_KEY)

    payload = build_prompt_data(listing_request)

    system_prompt = """
You are a professional e-commerce copywriter.

Your job is to write listings that SELL.

Focus on:
- clarity
- trust
- buyer intent
- search keywords

Rules:

Do not invent specifications.
Use natural human language.
Avoid AI-like wording.

Return JSON only.
"""

    user_prompt = f"""
Generate a marketplace listing from this data:

{json.dumps(payload, ensure_ascii=False, indent=2)}

Rules:
- Platform matters. Adapt style for the selected platform.
- Keep the title concise and clickable.
- Description should be natural, persuasive, and honest.
- Bullet points should highlight the most important buyer-facing details.
- Tags should be short and useful for search.
- Price suggestions should be realistic estimates in GBP.
- Never mention that this was generated by AI.
Return JSON only.
"""

    response = client.responses.create(
        model="gpt-5-mini",
        input=[
            {"role": "system", "content": system_prompt},
            {"role": "user", "content": user_prompt},
        ],
    )

    raw_text = response.output_text
    data = json.loads(raw_text)

    bullet_points = "\n".join(data.get("bullet_points", []))
    tags = ", ".join(data.get("tags", []))

    result = ListingResult.objects.create(
        request=listing_request,
        title=data.get("title", "")[:255],
        description=data.get("description", ""),
        bullet_points=bullet_points,
        tags=tags[:255],
        quick_sale_price=_to_decimal(data.get("quick_sale_price")),
        fair_price=_to_decimal(data.get("fair_price")),
        premium_price=_to_decimal(data.get("premium_price")),
    )

    return result