# Generated by Django 5.2.12 on 2026-03-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook Marketplace'), ('ebay', 'eBay'), ('vinted', 'Vinted')], max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('parts', 'For Parts / Repair')], max_length=20)),
                ('tone', models.CharField(choices=[('simple', 'Simple'), ('premium', 'Premium'), ('fast_sale', 'Fast Sale')], max_length=20)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('size_details', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('flaws', models.TextField(blank=True)),
                ('raw_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
