# Generated by Django 5.2.12 on 2026-03-09 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('bullet_points', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('quick_sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fair_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('premium_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='listings.listingrequest')),
            ],
        ),
    ]
