# Generated by Django 5.2.12 on 2026-03-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listingresult_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listingresult',
            name='image',
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='listing_images/'),
        ),
    ]
