# Generated by Django 5.2.12 on 2026-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listingresult_image_listingrequest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='listingrequest',
            name='comps_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listingrequest',
            name='ebay_comps_summary',
            field=models.TextField(blank=True),
        ),
    ]
